---
name: test

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
env:
  DEBIAN_FRONTEND: noninteractive
  RUN_TEST_ON_GITHUB_ACTIONS: 1
jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 5m
  test:
    strategy:
      matrix:
        go: ["1.19.x", "1.18.x"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          go test -race -covermode=atomic -coverprofile=prof.out ./...
        shell: bash
      - if: matrix.os == 'ubuntu-latest'
        run: |
          ./test.bash
          make testconvention
      - if: matrix.os == 'windows-latest'
        run: |
          go build -o check-log/check-log.exe ./check-log
          go build -o check-procs/check-procs.exe ./check-procs
          go build -o check-windows-eventlog/check-windows-evenglog.exe ./check-windows-eventlog
          go build -o check-ntservice/check-ntservice.exe ./check-ntservice
          go build -o check-disk/check-disk.exe ./check-disk
          go build -o check-uptime/check-uptime.exe ./check-uptime
          go build -o check-tcp/check-tcp.exe ./check-tcp
      - uses: shogo82148/actions-goveralls@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-profile: prof.out
          parallel: true
          flag-name: ${{ matrix.os }}_go${{ matrix.go }}
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y rpm devscripts debhelper fakeroot crossbuild-essential-arm64
          mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - run: make clean build rpm deb
      - uses: actions/upload-artifact@v3
        with:
          name: linux-build-artifacts
          path: |
            ~/rpmbuild/RPMS/*/*.rpm
            packaging/*.deb
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: linux-build-artifacts
          path: artifacts/
      - uses: mackerelio/staging-release-update-action@main
        if: github.ref == 'refs/heads/master'
        with:
          directory: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag: staging
      - uses: mackerelio/create-release-action@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          directory: artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: "refs/tags/v"
          bump-up-branch-prefix: "bump-version-"
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,action,eventName,ref,workflow,job,took
          username: go-check-plugins-release
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MACKEREL_SLACK_WEBHOOK_URL }}
